Repository hackclub/hcb-mobile, pull requests merged in 2025-05, with the labels that each got.

#166 Fix GeoPatterns mismatch by implementing custom pattern library (#16)
  README.md
  package-lock.json
  package.json
  src/components/PaymentCard.tsx
  src/util.ts
Labels: bug

#176 Fix Logging Out bug & Offline caching
  App.tsx
  babel.config.js
  metro.config.js
  package-lock.json
  package.json
  src/AppContent.tsx
  src/AuthProvider.tsx
  src/auth.ts
  src/cacheProvider.ts
  src/components/organizations/transfer/Disbursement.tsx
  src/components/transaction/ReceiptList.tsx
  src/lib/client.ts
  src/lib/useOffline.ts
  src/pages/Receipts.tsx
  src/pages/Settings.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/organization/index.tsx
Labels: bug, enhancement

#183 Prompt merchant education one time on first donation load
  package-lock.json
  package.json
  src/pages/organization/Donation.tsx
Labels: Tap to Pay on iPhone

#184 Rework of Settings screen!
  App.tsx
  src/AppContent.tsx
  src/Navigator.tsx
  src/ThemeContext.tsx
  src/components/organizations/PlaygroundBanner.tsx
  src/lib/NavigatorParamList.ts
  src/lib/client.ts
  src/pages/Settings.tsx
  src/pages/organization/Donation.tsx
  src/pages/organization/index.tsx
  src/pages/settings/About.tsx
  src/pages/settings/AppIconSelector.tsx
  src/pages/settings/Settings.tsx
  src/pages/settings/Tutorials.tsx
Labels: enhancement, Tap to Pay on iPhone

#186 iOS only Tap to Pay Banner
  src/components/PaymentCard.tsx
  src/components/organizations/TapToPayBanner.tsx
  src/pages/organization/index.tsx
Labels: Tap to Pay on iPhone

#188 [bug] fix card overflow
  src/pages/card.tsx
Labels: bug
